### ISSUE TITLE
Первый этап

### ISSUE THREAD

**Issue by seralekseenko** [vpodgurskiy/textAnalyzer-2#1]
Реализуйте парсинг и выполнение различных ключей и команд для анализатора текста.
Для начала такой парсер стоит сделать своими руками. Это необходимо для лучшего понимания работы библиотек, которые парсят входящие параметры.

Полезная информация
State machine:
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9_%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82 
https://www.bvn13.tk/posts/java-simple-final-state-machine 
https://ru.hexlet.io/courses/js-abp/lessons/fsm/theory_unit

Задача
Реализуйте парсинг входных ключей:
- строка без ключей - приложение работает по умолчанию, анализируя все подряд;
- вывод инструкции, никакого анализа. (-h, --h);
- работаем только с символами в тексте. Словарная статистика игнорируется или вообще не анализируется. (-someKey);
- работаем только со словами. Символьная статистика игнорируется или вообще не анализируется. (-someKey); 

Не забываем про тесты и документацию! Документация как в основном коде так и в тестах.
Наименование тестов должно быть лаконичным и “говорящим”.

**Comment by seralekseenko** [comment]
Я уже и сам зачитался по этим темам )))

**Comment by vpodgurskiy** [comment]
1. Думаю еще надо вынести условия с проверкой параметров из CLI.
2. Тесты еще не написал, в процессе...
3. Вопрос, как мне имплементировать интерфейс, а метод при этом использовать из другого класса? Если я наследуюсь от этого класса, я не могу менять тип возвращаемого значения у метода parse. Т.е. я хочу чтобы была возможность создавать свои методы с таким же названием через интерфейс, а так же при желании использовать методы из других классов.

**Comment by seralekseenko** [comment]
3) так в интерфейсе сделай метод типизированным. И в каждом потомке ты будешь возвращать тот тип, который необходимо.

**Comment by vpodgurskiy** [comment]
переделал структуру. Мне кажется уже лучше. Еще есть недочеты, буду доделывать...

**Comment by seralekseenko** [comment]
Оталось:
- упростить некоторые ключи или сделать их реально говорящими, а вот это не туда не сюда...
- описать каждый ключ докой и добавить в ХЕЛП.
